use anyhow::{Context, Result, bail};
use chrono::{DateTime, NaiveDate, Utc};
use serde::{Deserialize, Serialize};
use std::{collections::BTreeMap, fs, path::Path};

/// Which implementation supplies the pipeline's inputs. The rest of the
/// pipeline never learns where the data came from — it asks a source for
/// articles and bars and normalizes whatever it gets, so the stages differ
/// only in this value (spec: "Fixture, curated-file, and API modes must
/// produce the same normalized schemas").
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SourceMode {
    /// Made-up data generated by code (Stage 0).
    Fixture,
    /// Real vendor payloads read off disk (Stage 1).
    SavedFiles,
}

fn default_source_mode() -> SourceMode {
    SourceMode::Fixture
}

fn default_max_modal_share() -> f64 {
    0.8
}

/// Thresholds for the spec's 5-value decision vocabulary.
///
/// Every one lives in config rather than in the verdict function. Stage 3 will
/// need to tune and audit these against a real two-year dataset, and a gate
/// baked into a constant is a gate nobody can adjust or argue with.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerdictThresholds {
    /// Above this share of QUARANTINED (not excluded) articles, publication
    /// times are too unreliable to trust any result -> `stop`.
    pub max_quarantine_rate: f64,
    /// Below this share of articles containing at least one lexicon term, the
    /// scorer is not reading the news it is given -> `expand sources`.
    pub min_lexicon_hit_rate: f64,
    /// Below this share of configured sources actually contributing articles,
    /// the source mixture is thinner than it claims -> `expand sources`.
    pub min_source_coverage: f64,
    /// Below this many articles per signal, there is not enough news to
    /// aggregate -> `expand data`.
    pub min_articles_per_signal: f64,
    /// Fewer observations than this and a configuration cannot be judged at all
    /// -> `expand data`. `shuffled_spread` returns 0.0 by fiat below 3
    /// observations — it invents a baseline rather than computing one — so a
    /// tiny group can "beat" a fabricated zero and report `continue`.
    pub min_observations: u32,
    /// The observed spread must beat the baseline by at least this much.
    ///
    /// Without it, `observed > shuffled` is decided by floating-point noise:
    /// two spreads equal to fifteen decimal places still compare as `>` because
    /// they were summed in a different order. Three fixture configurations
    /// reported `continue` on a 1e-18 difference. An edge visible only past the
    /// 15th decimal place is rounding, not signal.
    pub min_spread_margin: f64,
}

impl Default for VerdictThresholds {
    fn default() -> Self {
        Self {
            max_quarantine_rate: 0.10,
            // Raised from 0.20 when the scorer was replaced (design.md Decision
            // 20). The old value was calibrated to a broken scorer and the old
            // scorer cleared it by 0.002. LM+VADER reads ~82% of the real
            // sample, so this is a real floor now, not a formality.
            min_lexicon_hit_rate: 0.60,
            min_source_coverage: 0.50,
            min_articles_per_signal: 1.0,
            min_observations: 30,
            // 1 basis point. Below this the "edge" is smaller than a rounding
            // error on a single trade's cost, let alone tradable.
            min_spread_margin: 0.0001,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PipelineConfig {
    pub run_id: String,
    pub output_root: String,
    pub generated_at: DateTime<Utc>,
    /// Defaulted so the Stage 0 config, written before sources were swappable,
    /// keeps loading unchanged.
    #[serde(default = "default_source_mode")]
    pub news_source: SourceMode,
    #[serde(default = "default_source_mode")]
    pub price_source: SourceMode,
    /// Required when either source is `saved_files`; ignored otherwise.
    #[serde(default)]
    pub saved_files_dir: Option<String>,
    /// The window this dataset is *asserted* to cover. Articles published
    /// outside it are excluded rather than silently widening the manifest —
    /// the spec requires the manifest record "exact date boundaries", and a
    /// boundary that quietly moves to fit the data is not a boundary. Absent
    /// (as in the Stage 0 fixture config) means "accept whatever the source
    /// returns".
    #[serde(default)]
    pub dataset_date_start: Option<NaiveDate>,
    #[serde(default)]
    pub dataset_date_end: Option<NaiveDate>,
    pub symbols: Vec<String>,
    pub source_sets: Vec<String>,
    pub news_windows_minutes: Vec<i64>,
    pub measurement_horizons_minutes: Vec<i64>,
    pub price_interval_minutes: i64,
    pub long_quantile: f64,
    pub short_quantile: f64,
    /// Above this share of observations tied on one sentiment value, the
    /// distribution has no usable resolution and the configuration is treated
    /// as degenerate: no trades, and an `expand sources` verdict. Configurable
    /// rather than hardcoded because Stage 3 will need to tune and audit it.
    #[serde(default = "default_max_modal_share")]
    pub max_modal_share: f64,
    #[serde(default)]
    pub verdict_thresholds: VerdictThresholds,
    pub costs_bps: Vec<f64>,
    pub holidays: Vec<NaiveDate>,
    pub early_closes: BTreeMap<NaiveDate, String>,
    pub theme_symbol_map: BTreeMap<String, Vec<String>>,
    /// Constituent ticker -> ETFs it moves. `AAPL -> [QQQ, SPY]`.
    ///
    /// The source probe found that Massive tags news to *companies*, not ETFs:
    /// only 4 of 677 articles in the sample week mentioned SPY/QQQ/DIA/IWM at
    /// all, while AMZN alone had 57. Without this map, an article tagged
    /// `[AMZN]` maps to no symbol we trade, gets excluded as
    /// `no_relevant_symbol`, and the ETFs starve.
    ///
    /// This is the spec's own relevance design, not a workaround: "Ticker tags
    /// are one relevance input, not the only one. Configured mappings propagate
    /// direct company news to linked equities, sector and theme news to relevant
    /// equities and ETFs."
    #[serde(default)]
    pub constituent_etf_map: BTreeMap<String, Vec<String>>,
    pub macro_symbols: Vec<String>,
}

impl PipelineConfig {
    pub fn load(path: impl AsRef<Path>) -> Result<Self> {
        let path = path.as_ref();
        let text = fs::read_to_string(path)
            .with_context(|| format!("failed to read config {}", path.display()))?;
        let config: Self = serde_json::from_str(&text)
            .with_context(|| format!("failed to parse config {}", path.display()))?;
        config.validate()?;
        Ok(config)
    }

    pub fn validate(&self) -> Result<()> {
        if self.run_id.trim().is_empty() {
            bail!("run_id must not be empty");
        }
        if self.symbols.is_empty() {
            bail!("symbols must not be empty");
        }
        if self.news_windows_minutes.is_empty() {
            bail!("news_windows_minutes must not be empty");
        }
        if self
            .news_windows_minutes
            .iter()
            .any(|minutes| *minutes <= 0)
        {
            bail!("news_windows_minutes must be positive");
        }
        if self.measurement_horizons_minutes.is_empty() {
            bail!("measurement_horizons_minutes must not be empty");
        }
        if self
            .measurement_horizons_minutes
            .iter()
            .any(|minutes| *minutes <= 0)
        {
            bail!("measurement_horizons_minutes must be positive");
        }
        if self.source_sets.is_empty() {
            bail!("source_sets must not be empty");
        }
        if !(0.0..1.0).contains(&self.short_quantile) {
            bail!("short_quantile must be between 0 and 1");
        }
        if !(0.0..1.0).contains(&self.long_quantile) {
            bail!("long_quantile must be between 0 and 1");
        }
        if self.short_quantile >= self.long_quantile {
            bail!("short_quantile must be below long_quantile");
        }
        if self.uses_saved_files() && self.saved_files_dir.is_none() {
            bail!("saved_files_dir is required when news_source or price_source is saved_files");
        }
        Ok(())
    }

    pub fn uses_saved_files(&self) -> bool {
        self.news_source == SourceMode::SavedFiles || self.price_source == SourceMode::SavedFiles
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn stage0() -> PipelineConfig {
        PipelineConfig::load("configs/stage0_fixture.json").unwrap()
    }

    #[test]
    fn stage0_config_defaults_to_the_fixture_source_without_naming_it() {
        // configs/stage0_fixture.json predates swappable sources and names no
        // source at all; it must keep loading and keep meaning "fixture".
        let config = stage0();

        assert_eq!(config.news_source, SourceMode::Fixture);
        assert_eq!(config.price_source, SourceMode::Fixture);
        assert!(!config.uses_saved_files());
    }

    #[test]
    fn saved_files_source_without_a_directory_is_a_config_error() {
        let mut config = stage0();
        config.news_source = SourceMode::SavedFiles;
        config.saved_files_dir = None;

        let error = config.validate().unwrap_err().to_string();

        assert!(error.contains("saved_files_dir"), "got: {error}");
    }

    #[test]
    fn an_unknown_source_name_is_a_parse_error_not_a_panic() {
        let json = r#"{"run_id":"x","output_root":"artifacts","generated_at":"2026-07-09T00:00:00Z",
            "news_source":"carrier_pigeon","symbols":["SPY"],"source_sets":["finance_only"],
            "news_windows_minutes":[60],"measurement_horizons_minutes":[60],"price_interval_minutes":60,
            "long_quantile":0.8,"short_quantile":0.2,"costs_bps":[0.0],"holidays":[],"early_closes":{},
            "theme_symbol_map":{},"macro_symbols":[]}"#;

        let result: Result<PipelineConfig, _> = serde_json::from_str(json);

        assert!(result.is_err());
    }
}
